### ISSUE TITLE
Failed to configure CMake file

### ISSUE THREAD

**Issue by vsamy** [jrl-umi3218/eigen-qld#17]
OS: Windows
Compiler: MinGW - GCC 8.1.0 - gfortran

The error: [cmake] CMake Error: install(EXPORT "eigen-qldTargets" ...) includes target "eigen-qld" which requires target "qld_fortran" that is not in the export set.

Any idea how to fix this?

Thank you :)

**Comment by gergondet** [comment]
Can you try setting the cmake option `USE_FORTRAN_SUBDIRECTORY` off?

**Comment by vsamy** [comment]
In that case there is no problem.

**Comment by gergondet** [comment]
> But failed to compile

This is related to https://github.com/jrl-umi3218/jrl-cmakemodules/pull/412

I've update the cmake submodule on this repo. Can you try again?

> If I try to build with MSVC and this parameter OFF

Yes. It cannot work in MSVC without this parameter because MSVC doesn't ship a Fortran compiler

**Comment by vsamy** [comment]
It works thanks!!
